name: Deploy to Production

on:
  push:
    branches:
      - main
  # schedule: # Run workflow automatically
  #   - cron: '0 1 * * *' # Runs every day at 1:00 AM (min hour day month)
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build components 🔧
        # .nojekyll: do not ignore _ dirs
        run: |
          npm ci
          npm run build
          touch build/.nojekyll
        #     CI: false # true -> fails on warning

      - name: Download versions from 2026
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f
        with:
          tag: '2026'
          fileName: 'dist.tar.gz'

      - name: Extract versions from 2026
        run: |
          mkdir -p build/2026
          tar -xvf dist.tar.gz --directory build/2026

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: 'build'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
